# Generated by Django 5.2.8 on 2026-04-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_administradora_vinculocondominio'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='administradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidades.administradora', verbose_name='Administradora'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('dev', 'Desenvolvedor'), ('fin', 'Financeiro'), ('fat', 'Faturista'), ('adm', 'Administrador'), ('cli', 'Client')], default='adm', max_length=3),
        ),
    ]
