# Generated by Django 5.2.8 on 2026-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_administradora_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
