# Generated by Django 5.2.8 on 2026-05-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='empresa',
        ),
    ]
