# Generated by Django 5.2.8 on 2026-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('dev', 'Desenvolvedor'), ('fin', 'Financeiro'), ('fat', 'Faturista'), ('adm', 'Usuário da Administradora'), ('cli', 'Cliente(Condomínio)')], default='adm', max_length=3),
        ),
    ]
