# Generated by Django 5.2.8 on 2026-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_nome_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
    ]
