# Generated by Django 5.2.8 on 2026-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_primeiro_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
