# Generated by Django 5.2.8 on 2026-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_username_unique_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último reset de senha'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_count',
            field=models.IntegerField(default=0, verbose_name='Contador de resets'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de reset de senha'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de criação do token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de expiração do token'),
        ),
    ]
