# Generated by Django 5.2.8 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_last_password_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('dev', 'Desenvolvedor'),
                    ('fin', 'Financeiro'),
                    ('dep', 'Departamento Pessoal'),
                    ('fat', 'Faturista'),
                    ('adm', 'Usuário da Administradora'),
                    ('cli', 'Cliente(Condomínio)'),
                ],
                default='adm',
                max_length=3
            ),
        ),
    ]
