# Generated by Django 5.2.8 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_multi_administradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('dev', 'Desenvolvedor'), ('fin', 'Financeiro'), ('dep', 'Departamento Pessoal'), ('fat', 'Faturista'), ('adm', 'Usuário da Administradora'), ('sup', 'Supervisor da Administradora'), ('cli', 'Cliente(Condomínio)')], default='adm', max_length=3),
        ),
    ]
