# Generated by Django 5.2.8 on 2026-07-21 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Arquivo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('value_cents', models.IntegerField(default=0, verbose_name='Valor em Centavos')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('uploader_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Responsável')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='operacional/boletos/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_operacionais', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_num', models.CharField(max_length=100, verbose_name='Número da Fatura')),
                ('emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('estipulante_nome', models.CharField(max_length=255, verbose_name='Nome do Estipulante')),
                ('estipulante_cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ do Estipulante')),
                ('administradora_nome', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da Administradora')),
                ('uploader_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Responsável')),
                ('manual_status', models.CharField(blank=True, choices=[('faturado', 'Faturado'), ('atrasado', 'Confirmar Pagamento'), ('aprovado', 'Boleto VR Enviado'), ('pago', 'Pago')], max_length=20, null=True, verbose_name='Status Manual')),
                ('total_cents', models.IntegerField(default=0, verbose_name='Total em Centavos')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='operacional/faturas/', verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_operacionais', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoEstipulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ')),
                ('valor_cents', models.IntegerField(default=0, verbose_name='Valor em Centavos')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_credito', models.DateField(blank=True, null=True, verbose_name='Data de Crédito')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('sent_to_cp', models.BooleanField(default=False, verbose_name='Enviado para Contas a Pagar')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_estipulantes', to='operacional.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Co-Estipulante',
                'verbose_name_plural': 'Co-Estipulantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FaturaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('image_data', models.TextField(blank=True, null=True, verbose_name='Imagem (base64)')),
                ('author_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Autor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operacional.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Comentário da Fatura',
                'verbose_name_plural': 'Comentários das Faturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
