# Generated by Django 5.2.8 on 2025-11-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_produto', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código do Produto')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto/Benefício')),
            ],
            options={
                'verbose_name': 'Produto/Benefício',
                'verbose_name_plural': 'Produtos/Benefícios',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competencia', models.DateField(verbose_name='Data de Competência (MM/AAAA)')),
                ('valor_beneficio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Benefício')),
                ('quantidade_dias', models.IntegerField(verbose_name='Quantidade de Dias/Unidades')),
                ('empresa_cnpj', models.ForeignKey(db_column='empresa_cnpj', on_delete=django.db.models.deletion.CASCADE, to='entidades.condominio', verbose_name='Condomínio CNPJ')),
                ('funcionario_cpf', models.ForeignKey(db_column='funcionario_cpf', on_delete=django.db.models.deletion.CASCADE, to='entidades.funcionario', verbose_name='Funcionário CPF')),
                ('produto_codigo', models.ForeignKey(db_column='produto_codigo', on_delete=django.db.models.deletion.CASCADE, to='beneficios.produto', verbose_name='Produto Código')),
            ],
            options={
                'verbose_name': 'Movimentação de Benefício',
                'verbose_name_plural': 'Movimentações de Benefício',
                'unique_together': {('empresa_cnpj', 'funcionario_cpf', 'produto_codigo', 'data_competencia')},
            },
        ),
    ]
