# Generated by Django 5.2.8 on 2025-11-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
        ('entidades', '0002_funcionario_departamento_alter_condominio_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='data_competencia',
            field=models.DateField(verbose_name='Data de Competência'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='empresa_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.condominio', verbose_name='Condomínio'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='funcionario_cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='produto_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='quantidade_dias',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='valor_beneficio',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Benefício'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código do Produto'),
        ),
    ]
