# Generated by Django 5.2.8 on 2026-04-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_alter_movimentacaobeneficio_data_competencia_and_more'),
        ('upload', '0007_alter_fileupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Importação')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('registros_processados', models.IntegerField(default=0, verbose_name='Registros Processados')),
                ('erros', models.JSONField(default=list, verbose_name='Erros')),
                ('file_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.fileupload', verbose_name='Arquivo Carregado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaobeneficio',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='beneficios.importacao', verbose_name='Importação'),
        ),
    ]
