# Generated by Django 5.2.8 on 2026-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0003_importacao_movimentacaobeneficio_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
    ]
