# Generated by Django 5.2.8 on 2026-04-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0004_importacao_url'),
        ('entidades', '0004_gerente_vinculocondominio_gerentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência (Mês/Ano)')),
                ('arquivo_unificado_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Arquivo Unificado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='beneficios.importacao', verbose_name='Importação')),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaturamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_boleto', models.URLField(max_length=500, verbose_name='URL Boleto')),
                ('url_nota_debito', models.URLField(max_length=500, verbose_name='URL Nota Débito')),
                ('url_nota_fiscal', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Nota Fiscal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_faturamento', to='entidades.condominio', verbose_name='Condomínio')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='beneficios.faturamento', verbose_name='Faturamento')),
            ],
            options={
                'verbose_name': 'Documento de Faturamento',
                'verbose_name_plural': 'Documentos de Faturamento',
                'unique_together': {('faturamento', 'condominio')},
            },
        ),
    ]
