# Generated by Django 5.2.8 on 2026-04-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0005_faturamento_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progresso (%)'),
        ),
    ]
