# Generated by Django 5.2.8 on 2026-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0006_faturamento_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='importacao',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Vigência'),
        ),
        migrations.AddField(
            model_name='importacao',
            name='vigencia_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Vigência'),
        ),
    ]
