# Generated by Django 5.2.8 on 2026-04-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0007_add_administradora_to_faturamento'),
        ('beneficios', '0007_importacao_data_vencimento_importacao_vigencia_fim_and_more'),
    ]

    operations = [
    ]
