# Generated by Django 5.2.8 on 2026-04-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0008_merge_20260428_1209'),
        ('entidades', '0004_gerente_vinculocondominio_gerentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ALIMENTACAO', 'Alimentação'), ('AUX_ALIMENTACAO', 'Auxílio Alimentação'), ('REFEICAO', 'Refeição'), ('AUX_REFEICAO', 'Auxílio Refeição'), ('AUTO', 'Auto'), ('MULTI_AUXILIO', 'Multi Auxílio'), ('MULTI_MOBILIDADE', 'Multi Mobilidade'), ('MULTI_PREMIACAO', 'Multi Premiação')], max_length=30, null=True, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='administradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos', to='entidades.administradora', verbose_name='Administradora'),
        ),
    ]
