# Generated by Django 5.2.8 on 2026-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0009_add_tipo_to_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
