# Generated by Django 5.2.8 on 2026-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0010_add_status_aguardando_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total da Importação'),
        ),
    ]
