# Generated by Django 5.2.8 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0011_importacao_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='total_funcionarios',
            field=models.IntegerField(default=0, verbose_name='Total de Registros'),
        ),
        migrations.AddField(
            model_name='movimentacaobeneficio',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('CANCELADO', 'Cancelado'), ('EM FATURAMENTO', 'Em Faturamento'), ('FATURADO', 'Faturado')], default='APROVADO', max_length=30, verbose_name='Status'),
        ),
    ]
