# Generated by Django 5.2.8 on 2026-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0012_importacao_total_funcionarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaobeneficio',
            name='status',
        ),
        migrations.AddField(
            model_name='movimentacaobeneficio',
            name='fat_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FATURADO', 'Faturado'), ('FAILED', 'Falhou')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='movimentacaobeneficio',
            name='importacao_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=30, verbose_name='Status da Importação'),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FATURADO', 'Faturado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
