# Generated by Django 5.2.8 on 2026-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0013_remove_movimentacaobeneficio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='fat_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FATURADO', 'Faturado'), ('FAILED', 'Falhou')], default='PENDING', max_length=30, null=True, verbose_name='Status do Faturamento'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='importacao_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], max_length=30, verbose_name='Status da Importação'),
        ),
    ]
