# Generated by Django 5.2.8 on 2026-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0014_alter_movimentacaobeneficio_fat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='fat_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FATURADO', 'Faturado'), ('FAILED', 'Falhou')], max_length=30, null=True, verbose_name='Status do Faturamento'),
        ),
    ]
