# Generated by Django 5.2.8 on 2026-05-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0015_alter_movimentacaobeneficio_fat_status'),
        ('entidades', '0008_alter_administradora_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimentacaobeneficio',
            unique_together={('importacao', 'empresa_cnpj', 'funcionario_cpf', 'produto_codigo', 'data_competencia')},
        ),
    ]
