# Generated by Django 5.2.8 on 2026-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0016_alter_movimentacaobeneficio_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='modelo_importacao',
            field=models.CharField(choices=[('VR-BENEFICIOS', 'VR Benefícios'), ('VR-AUTO', 'VR Auto'), ('OUTRO', 'Outro')], default='VR-BENEFICIOS', max_length=20, verbose_name='Modelo de Importação'),
        ),
    ]
