# Generated by Django 5.2.8 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0017_importacao_modelo_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='modelo_importacao',
            field=models.CharField(choices=[('VR-BENEFICIOS', 'VR Benefícios'), ('VR-AUTO', 'VR Auto'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Modelo de Importação'),
        ),
    ]
