# Generated by Django 5.2.8 on 2026-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0018_alter_importacao_modelo_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_fornecedora',
            field=models.CharField(default='000000', max_length=50, verbose_name='Código da Fornecedora'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedora',
            field=models.CharField(choices=[('VR', 'VR'), ('TICKET', 'Ticket'), ('OUTRO', 'Outro')], default='VR', max_length=20, verbose_name='Fornecedora'),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='modelo_importacao',
            field=models.CharField(choices=[('VR-BENEFICIOS', 'VR Benefícios'), ('VT-AUTO', 'VT Auto'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Modelo de Importação'),
        ),
    ]
