# Generated by Django 5.2.8 on 2026-06-26 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0020_add_indexes_status_and_competencia'),
        ('entidades', '0010_alter_administradora_valor_max_beneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_integracao', models.CharField(max_length=100, unique=True, verbose_name='ID Integração')),
                ('status', models.CharField(choices=[('EM_EMISSAO', 'Em Emissão'), ('EMITIDO', 'Emitido'), ('FAILED', 'Falhou')], db_index=True, default='EM_EMISSAO', max_length=20, verbose_name='Status')),
                ('protocolo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo')),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Verificação')),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do PDF')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload Enviado')),
                ('resposta', models.JSONField(blank=True, null=True, verbose_name='Resposta da API')),
                ('erro', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='entidades.condominio', verbose_name='Condomínio')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='beneficios.faturamento', verbose_name='Faturamento')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-created_at'],
            },
        ),
    ]
