# Generated by Django 5.2.8 on 2026-07-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0021_notafiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento')),
                ('dt_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('fatura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura')),
                ('codigo_de_barra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barra')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code')),
                ('qr_imagem', models.TextField(blank=True, null=True, verbose_name='QR Imagem')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('nome_cobrado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Cobrado')),
                ('cnpj_cobrado', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ Cobrado')),
                ('cedente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cedente')),
                ('cnpj_cedente', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ do Cedente')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('deducoes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deduções')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('nosso_numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nosso Número')),
                ('identificador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador')),
                ('baixa', models.BooleanField(default=False, verbose_name='Baixa')),
                ('dt_baixa', models.DateField(blank=True, null=True, verbose_name='Data da Baixa')),
                ('obs_baixa', models.TextField(blank=True, null=True, verbose_name='Observação da Baixa')),
                ('NFs_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='NFs ID')),
                ('Numero_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('url_nota', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('faturamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletos_rel', to='beneficios.faturamento', verbose_name='Faturamento')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-vencimento'],
            },
        ),
    ]
