# Generated by Django 5.2.8 on 2026-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0022_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='match',
            field=models.BooleanField(default=False, verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='NFs_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='NFs ID'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='Numero_nota',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='documento',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='url_nota',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='URL da Nota'),
        ),
    ]
