# Generated by Django 5.2.8 on 2026-07-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0023_boleto_match_alter_boleto_nfs_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
