# Generated by Django 5.2.8 on 2026-07-14 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0025_remove_importacao_url_importacao_arquivo_s3'),
        ('entidades', '0012_idx_importacao_adm_data'),
        ('upload', '0012_fileupload_arquivo_s3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importacao',
            index=models.Index(fields=['administradora', '-data_importacao'], name='idx_importacao_adm_data'),
        ),
    ]
