# Generated by Django 5.2.8 on 2026-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0026_idx_importacao_adm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
    ]
