# Generated by Django 5.2.8 on 2026-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0027_add_data_recebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='arquivo_s3_editado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Arquivo S3 Editado'),
        ),
    ]
