# Generated by Django 5.2.8 on 2026-07-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_add_comprado_status'),
        ('beneficios', '0028_importacao_arquivo_s3_editado'),
    ]

    operations = [
    ]
