# Generated by Django 5.2.8 on 2026-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0029_merge_20260721_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('FATURADO', 'Faturado'), ('CONFIRMAR_PAGAMENTO', 'Confirmar Pagamento'), ('BOLETO_VR_ENVIADO', 'Boleto VR Enviado'), ('PAGO', 'Pago'), ('COMPRADO', 'Comprado'), ('CANCELADO', 'Cancelado'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaobeneficio',
            name='importacao_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('FATURADO', 'Faturado'), ('CONFIRMAR_PAGAMENTO', 'Confirmar Pagamento'), ('BOLETO_VR_ENVIADO', 'Boleto VR Enviado'), ('PAGO', 'Pago'), ('COMPRADO', 'Comprado'), ('CANCELADO', 'Cancelado'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], max_length=30, verbose_name='Status da Importação'),
        ),
    ]
