# Generated by Django 5.2.8 on 2026-07-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0030_alter_importacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ALIMENTACAO', 'Alimentação'), ('AUTO', 'Auto'), ('REFEICAO', 'Refeição'), ('MULTI_HOME_OFFICE', 'Multi - Home Office'), ('BOAS_FESTAS', 'Boas Festas'), ('MULTI_ALIMENTACAO', 'Multi - Alimentação'), ('MULTI_VR_VA', 'Multi - VR+VA'), ('MULTI_REFEICAO', 'Multi - Refeição'), ('MULTI_MOBILIDADE', 'Multi - Mobilidade')], max_length=30, null=True, verbose_name='Tipo do Produto'),
        ),
    ]
