# Generated by Django 5.2.8 on 2026-07-22 19:18

from django.db import migrations


# Mapeamento de nomes/códigos de produto para o tipo normalizado.
MAPEAMENTO_PRODUTO_TIPO = {
    'Refeição': 'Refeição',
    'Multi Refeição': 'Multi - Refeição',
    'Alimentação': 'Alimentação',
    'Multi Alimentação': 'Multi - Alimentação',
    'Auto': 'Auto',
    'Mobilidade': 'Multi - Mobilidade',
    'VR Mobilidade': 'Multi - Mobilidade',
    'Multi Mobilidade': 'Multi - Mobilidade',
    'VR Multi Mobilidade': 'Multi - Mobilidade',
    'Cesta': 'Boas Festas',
    'Boas Festas': 'Boas Festas',
    'Auxílio Alimentação': 'Alimentação',
    'Multi Auxílio Alimentação': 'Multi - Alimentação',
    'Auxílio Refeição': 'Refeição',
    'Multi Auxílio Refeição': 'Multi - Refeição',
    'Multibenefício': 'Multi - VR+VA',
    'Multibenefícios': 'Multi - VR+VA',
    'Auxílio VR+VA': 'Multi - VR+VA',
    'Multi Auxílio VR+VA': 'Multi - VR+VA',
    'Multi Premiação': 'Multi - Home Office',
    'Multi - Home Office': 'Multi - Home Office',
    'VR Refeição': 'Refeição',
    'VR Alimentação': 'Alimentação',
    'VR Auto': 'Auto',
    'VR Alimentação Cesta': 'Boas Festas',
    'VR Boas Festas': 'Boas Festas',
    'VR Auxílio Alimentação': 'Alimentação',
    'VR Auxílio Refeição': 'Refeição',
    'VR Multibenefícios': 'Multi - VR+VA',
    'VR+VA': 'Multi - VR+VA',
    'VR Multi Refeição': 'Multi - Refeição',
    'VR Multi Alimentação': 'Multi - Alimentação',
    'VR Multi Alimentação Valor do crédito': 'Multi - Alimentação',
    'VR Multi Refeição Auxílio': 'Multi - Refeição',
    'VR Multi Alimentação Auxílio': 'Multi - Alimentação',
    'VR Multi VR+VA': 'Multi - VR+VA',
    'VR Multi - Home Office': 'Multi - Home Office',
}


def _normalizar_nome(nome):
    if not nome:
        return ''
    return str(nome).strip()


def _encontrar_tipo_por_nome(nome):
    nome = _normalizar_nome(nome)
    if not nome:
        return None

    # Correspondência exata
    if nome in MAPEAMENTO_PRODUTO_TIPO:
        return MAPEAMENTO_PRODUTO_TIPO[nome]

    # Correspondência parcial
    nome_lower = nome.lower()
    for chave, tipo in MAPEAMENTO_PRODUTO_TIPO.items():
        chave_lower = chave.lower()
        if chave_lower in nome_lower or nome_lower in chave_lower:
            return tipo

    return None


def atualizar_tipos_produtos(apps, schema_editor):
    Produto = apps.get_model('beneficios', 'Produto')

    # Mapeamento do display para o valor interno do campo tipo.
    # Deve refletir o TIPO_CHOICES do modelo Produto.
    TIPO_PARA_VALUE = {
        'Alimentação': 'ALIMENTACAO',
        'Auto': 'AUTO',
        'Refeição': 'REFEICAO',
        'Multi - Home Office': 'MULTI_HOME_OFFICE',
        'Boas Festas': 'BOAS_FESTAS',
        'Multi - Alimentação': 'MULTI_ALIMENTACAO',
        'Multi - VR+VA': 'MULTI_VR_VA',
        'Multi - Refeição': 'MULTI_REFEICAO',
        'Multi - Mobilidade': 'MULTI_MOBILIDADE',
    }

    produtos = Produto.objects.all()
    atualizados = 0

    for produto in produtos:
        tipo_display = _encontrar_tipo_por_nome(produto.nome)
        if not tipo_display:
            tipo_display = _encontrar_tipo_por_nome(produto.codigo_produto)

        if tipo_display:
            tipo_value = TIPO_PARA_VALUE.get(tipo_display)
            if tipo_value and produto.tipo != tipo_value:
                produto.tipo = tipo_value
                produto.save(update_fields=['tipo'])
                atualizados += 1

    print(f"Atualizados {atualizados} produtos para os novos tipos.")


def reverse_atualizar_tipos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0031_alter_produto_tipo'),
    ]

    operations = [
        migrations.RunPython(atualizar_tipos_produtos, reverse_atualizar_tipos),
    ]
