# Generated by Django 5.2.8 on 2026-07-22 19:19

from django.db import migrations


# Mapeamento do valor antigo do campo tipo para o novo valor.
MAPEAMENTO_TIPO_ANTIGO = {
    'AUX_ALIMENTACAO': 'ALIMENTACAO',
    'AUX_REFEICAO': 'REFEICAO',
    'MULTI_AUXILIO': 'MULTI_VR_VA',
    'MULTI_MOBILIDADE': 'MULTI_MOBILIDADE',
    'MULTI_PREMIACAO': 'MULTI_HOME_OFFICE',
    'MUILTI_MOBILIDADE': 'MULTI_MOBILIDADE',
}

# Mapeamento do codigo do produto para o tipo (VR).
MAPEAMENTO_CODIGO_TIPO = {
    '27': 'ALIMENTACAO',
    '28': 'AUTO',
    '201': 'BOAS_FESTAS',
    '202': 'BOAS_FESTAS',
    '204': 'ALIMENTACAO',
    '207': 'MULTI_VR_VA',
}


def _encontrar_tipo_por_nome(nome):
    if not nome:
        return None
    nome = str(nome).strip()
    nome_lower = nome.lower()

    palavras_chave = [
        ('ALIMENTACAO', ['alimentacao', 'alimenta']),
        ('REFEICAO', ['refeicao', 'refei']),
        ('AUTO', ['combustivel', 'auto', 'pec', 'vale card', 'car']),
        ('BOAS_FESTAS', ['cesta', 'boas festas', 'natal']),
        ('MULTI_MOBILIDADE', ['mobilidade', 'transporte', 'p-trans', 'bilhete', 'municipal', 'urbano', 'turismo', 'pass']),
        ('MULTI_HOME_OFFICE', ['premiacao', 'home office']),
        ('MULTI_VR_VA', ['multibeneficio', 'vr+va', 'flex']),
    ]

    for tipo, chaves in palavras_chave:
        for chave in chaves:
            if chave in nome_lower:
                return tipo

    return None


def corrigir_tipos_produtos(apps, schema_editor):
    Produto = apps.get_model('beneficios', 'Produto')

    produtos = Produto.objects.all()
    atualizados = 0

    for produto in produtos:
        tipo_value = None

        # 1. Se ja tiver um tipo valido novo, pula.
        if produto.tipo and produto.tipo not in MAPEAMENTO_TIPO_ANTIGO:
            continue

        # 2. Se tiver tipo antigo, converte para o novo.
        if produto.tipo in MAPEAMENTO_TIPO_ANTIGO:
            tipo_value = MAPEAMENTO_TIPO_ANTIGO[produto.tipo]

        # 3. Tenta pelo codigo do produto (VR).
        if not tipo_value:
            tipo_value = MAPEAMENTO_CODIGO_TIPO.get(str(produto.codigo_produto).strip())

        # 4. Tenta pelo nome.
        if not tipo_value:
            tipo_value = _encontrar_tipo_por_nome(produto.nome)

        if tipo_value:
            produto.tipo = tipo_value
            produto.save(update_fields=['tipo'])
            atualizados += 1

    print("Corrigidos %s produtos para os novos tipos." % atualizados)


def reverse_corrigir_tipos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0032_auto_20260722_1618'),
    ]

    operations = [
        migrations.RunPython(corrigir_tipos_produtos, reverse_corrigir_tipos),
    ]
