# Generated by Django 5.2.8 on 2026-07-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0034_pedido_cartao'),
        ('beneficios', '0036_limpar_produtos'),
    ]

    operations = [
    ]
