# Generated by Django 5.2.8 on 2026-07-28 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0038_alter_importacao_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Usuário que está processando esta importação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
