# Generated by Django 5.2.1 on 2026-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0040_faturamentoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentoarquivo',
            name='fatura_num',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
