# Generated by Django 5.2.8 on 2026-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0042_importacao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='erro_mensagem',
            field=models.TextField(blank=True, default='', help_text='Motivo da última falha da task de faturamento; exibido ao faturista (PA-011).', verbose_name='Erro do processamento'),
        ),
    ]
