# Generated by Django 5.2.8 on 2026-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0042_importacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentoarquivo',
            name='tipo',
            field=models.CharField(choices=[('boleto', 'Boleto'), ('nota_debito', 'Nota de débito'), ('nota_fiscal', 'Nota fiscal'), ('fatura', 'Fatura')], max_length=30),
        ),
    ]
