# Generated by Django 5.2.8 on 2025-11-17 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Condomínio')),
                ('tipo_local', models.CharField(max_length=50, verbose_name='Tipo de Local')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço (Rua)')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função/Cargo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('mae', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('endereco_rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
