# Generated by Django 5.2.8 on 2025-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento / Local'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cnpj',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço (Rua)'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Razão Social / Departamento'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='tipo_local',
            field=models.CharField(default='CONDOMINIO', max_length=50, verbose_name='Tipo de Local'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função/Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
