# Generated by Django 5.2.8 on 2026-04-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_funcionario_departamento_alter_condominio_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Administradora',
                'verbose_name_plural': 'Administradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.administradora', verbose_name='Administradora')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.condominio', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': 'Vínculo de Condomínio',
                'verbose_name_plural': 'Vínculos de Condomínios',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('administradora', 'condominio'), name='unique_administradora_condominio')],
            },
        ),
    ]
