# Generated by Django 5.2.8 on 2026-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_administradora_vinculocondominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='vinculocondominio',
            name='gerentes',
            field=models.ManyToManyField(blank=True, related_name='vinculos', to='entidades.gerente', verbose_name='Gerentes'),
        ),
    ]
