# Generated by Django 5.2.8 on 2026-05-08 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_gerente_vinculocondominio_gerentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='entidades.condominio', verbose_name='Condomínio'),
        ),
    ]
