# Generated by Django 5.2.8 on 2026-05-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_funcionario_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
