# Generated by Django 5.2.8 on 2026-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_funcionario_email_funcionario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
