# Generated by Django 5.2.8 on 2026-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_administradora_nome_fantasia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradora',
            options={'ordering': ['razao_social'], 'verbose_name': 'Administradora', 'verbose_name_plural': 'Administradoras'},
        ),
        migrations.RenameField(
            model_name='administradora',
            old_name='nome',
            new_name='razao_social',
        ),
        migrations.AddField(
            model_name='administradora',
            name='cartao_admin',
            field=models.BooleanField(default=True, verbose_name='Cartão Admin'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
