# Generated by Django 5.2.8 on 2026-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_alter_administradora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='valor_max_beneficio',
            field=models.DecimalField(decimal_places=2, default=2499.99, max_digits=10, verbose_name='Valor máximo por funcionário'),
        ),
    ]
