# Generated by Django 5.2.8 on 2026-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_administradora_valor_max_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradora',
            name='valor_max_beneficio',
            field=models.DecimalField(decimal_places=2, default=9999.99, max_digits=10, verbose_name='Valor máximo por funcionário'),
        ),
    ]
