# Generated by Django 5.2.8 on 2026-07-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_alter_administradora_valor_max_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='d_mais',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='D+'),
        ),
    ]
