# Generated by Django 5.2.8 on 2026-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_add_d_mais_administradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradora',
            name='d_mais',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='D+'),
        ),
    ]
