# Generated by Django 5.2.8 on 2026-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_idx_importacao_adm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='taxa_padrao_tipo',
            field=models.CharField(choices=[('PERC', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERC', max_length=4, verbose_name='Tipo da Taxa Padrão'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='taxa_padrao_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Taxa Padrão'),
        ),
        migrations.AddField(
            model_name='vinculocondominio',
            name='taxa_tipo',
            field=models.CharField(choices=[('PERC', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERC', max_length=4, verbose_name='Tipo da Taxa'),
        ),
        migrations.AddField(
            model_name='vinculocondominio',
            name='taxa_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Taxa'),
        ),
        migrations.AddField(
            model_name='vinculocondominio',
            name='usar_taxa_padrao',
            field=models.BooleanField(default=True, verbose_name='Usar Taxa Padrão da Administradora'),
        ),
    ]
