# Generated by Django 5.2.8 on 2026-07-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0027_add_data_recebimento'),
        ('entidades', '0013_administradora_taxa_padrao_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculocondominio',
            name='taxa_tipo',
        ),
        migrations.RemoveField(
            model_name='vinculocondominio',
            name='taxa_valor',
        ),
        migrations.RemoveField(
            model_name='vinculocondominio',
            name='usar_taxa_padrao',
        ),
        migrations.CreateModel(
            name='TaxaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_tipo', models.CharField(choices=[('PERC', 'Percentual (%)'), ('FIXO', 'Valor Fixo (R$)')], default='PERC', max_length=4, verbose_name='Tipo da Taxa')),
                ('taxa_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Taxa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, help_text='Se vazio, aplica a todos os produtos deste vínculo', null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficios.produto', verbose_name='Produto')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_config', to='entidades.vinculocondominio', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Configuração de Taxa',
                'verbose_name_plural': 'Configurações de Taxas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vinculo', 'produto'), name='unique_vinculo_produto')],
            },
        ),
    ]
