# Generated by Django 5.2.8 on 2026-07-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0014_remove_vinculocondominio_taxa_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='is_searched',
            field=models.BooleanField(default=False, help_text='Indica se o endereço já foi preenchido via consulta automática de CNPJ.', verbose_name='Endereço pesquisado automaticamente'),
        ),
    ]
