# Generated by Django 5.2.8 on 2026-07-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0015_condominio_is_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradora',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço (Rua)'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='administradora',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
    ]
