# Generated by Django 5.2.8 on 2026-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0033_auto_20260722_1619'),
        ('entidades', '0016_administradora_bairro_administradora_cep_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxaconfig',
            name='unique_vinculo_produto',
        ),
        migrations.AddField(
            model_name='taxaconfig',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ALIMENTACAO', 'Alimentação'), ('AUTO', 'Auto'), ('REFEICAO', 'Refeição'), ('MULTI_HOME_OFFICE', 'Multi - Home Office'), ('BOAS_FESTAS', 'Boas Festas'), ('MULTI_ALIMENTACAO', 'Multi - Alimentação'), ('MULTI_VR_VA', 'Multi - VR+VA'), ('MULTI_REFEICAO', 'Multi - Refeição'), ('MULTI_MOBILIDADE', 'Multi - Mobilidade')], help_text='Se preenchido, aplica a todos os produtos deste tipo', max_length=30, null=True, verbose_name='Tipo do Produto'),
        ),
        migrations.AddConstraint(
            model_name='taxaconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('produto__isnull', False)), fields=('vinculo', 'produto'), name='unique_vinculo_produto'),
        ),
        migrations.AddConstraint(
            model_name='taxaconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__isnull', False)), fields=('vinculo', 'tipo'), name='unique_vinculo_tipo'),
        ),
        migrations.AddConstraint(
            model_name='taxaconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('produto__isnull', True), ('tipo__isnull', True)), fields=('vinculo',), name='unique_vinculo_geral'),
        ),
    ]
