# Generated by Django 5.2.8 on 2025-11-19 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_fileupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': 'Upload de Arquivo', 'verbose_name_plural': 'Uploads de Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='processedfile',
            options={'verbose_name': 'Arquivo Processado', 'verbose_name_plural': 'Arquivos Processados'},
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='process_status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Processamento'), ('PARSED', 'Dados Extraídos, Pendente de Confirmação'), ('COMPLETED', 'Processamento Finalizado'), ('FAILED', 'Falha no Processamento')], default='PENDING', max_length=10, verbose_name='Status do Processamento'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.fileupload', verbose_name='Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Processado em'),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Processado por'),
        ),
    ]
