# Generated by Django 5.2.8 on 2025-12-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_fileupload_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
