# Generated by Django 5.2.8 on 2025-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfile',
            name='dados_requisicao',
            field=models.JSONField(default=dict, help_text='Dados completos da requisição POST (além de file_id)'),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
