# Generated by Django 5.2.8 on 2026-04-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_fileupload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
    ]
