# Generated by Django 5.2.8 on 2026-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='process_status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Processamento'), ('PARSED', 'Dados Extraídos, Pendente de Confirmação'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('COMPLETED', 'Processamento Finalizado'), ('FAILED', 'Falha no Processamento')], default='PENDING', max_length=30, verbose_name='Status do Processamento'),
        ),
    ]
