# Generated by Django 5.2.8 on 2026-07-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_fileupload_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='arquivo_s3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Arquivo S3'),
        ),
    ]
