# Generated by Django 5.2.8 on 2026-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_fileupload_arquivo_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='arquivo_s3_editado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Arquivo S3 Editado'),
        ),
    ]
