# Generated by Django 5.2.1 on 2026-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_fileupload_arquivo_s3_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='result_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados do Resultado (async)'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='process_status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Processamento'), ('PROCESSING', 'Processando'), ('PARSED', 'Dados Extraídos, Pendente de Confirmação'), ('AGUARDANDO_FATURAMENTO', 'Aguardando Faturamento'), ('COMPLETED', 'Processamento Finalizado'), ('FAILED', 'Falha no Processamento')], db_index=True, default='PENDING', max_length=30, verbose_name='Status do Processamento'),
        ),
    ]
